{ config, ... }:

{
  vale = {
    enable = true;
    lsp.enable = false;
  };
  git-hooks.hooks.vale.enable = false;

  assertions = [
    {
      assertion = config.vale.config.file == null && config.files.".vale.ini".copyMode == "seed";
      message = "The starter should be seeded independently of config selection.";
    }
    {
      assertion = !(config.tasks ? "devenv:vale:sync");
      message = "Vale sync should be disabled by default.";
    }
    {
      assertion = !(builtins.elem config.vale.lsp.package config.packages);
      message = "Disabling the Vale language server should omit its package.";
    }
  ];

  enterTest = ''
    set -euo pipefail

    command -v vale >/dev/null
    test -f .vale.ini
    test ! -L .vale.ini
    test -w .vale.ini
    test -z "''${VALE_CONFIG_PATH+x}"
    grep -q '^BasedOnStyles=Vale, Microsoft$' .vale.ini
    grep -q '^Packages=Microsoft$' .vale.ini
    grep -q '^MinAlertLevel=suggestion$' .vale.ini
    if grep -q 'Generated by devenv\|^StylesPath=' .vale.ini; then
      echo 'The starter should be user-owned and use the environment styles path' >&2
      exit 1
    fi

    # A seeded file belongs to the user after the first shell entry.
    printf '; user-owned\n' > .vale.ini
    (${config.tasks."devenv:files".exec})
    test "$(cat .vale.ini)" = '; user-owned'
  '';
}
