{ config, ... }:

{
  vale = {
    enable = true;
    sync.enable = true;
    config.file = "config dir/vale.ini";
    config.settings = {
      globalSection = {
        MinAlertLevel = "suggestion";
        Packages = [
          "./LocalPackage"
          "./SecondStyle"
        ];
        Vocab = [ "Project" ];
      };
      sections."*.md".BasedOnStyles = [
        "TestStyle"
        "SecondStyle"
      ];
    };
  };

  enterTest = ''
    set -euo pipefail

    command -v vale >/dev/null
    command -v vale-ls >/dev/null
    test -f "config dir/vale.ini"
    test ! -L "config dir/vale.ini"
    test -w "config dir/vale.ini"
    grep -q '^; Generated by devenv' "config dir/vale.ini"
    test "$VALE_CONFIG_PATH" = "$DEVENV_ROOT/config dir/vale.ini"
    test "$VALE_STYLES_PATH" = "$DEVENV_STATE/vale/styles"
    test -f "$VALE_STYLES_PATH/TestStyle/Forbidden.yml"
    test -f "$VALE_STYLES_PATH/SecondStyle/Forbidden.yml"
    grep -q '^Packages=./LocalPackage, ./SecondStyle$' "$VALE_CONFIG_PATH"
    grep -q '^BasedOnStyles=TestStyle, SecondStyle$' "$VALE_CONFIG_PATH"
    test -f "$VALE_STYLES_PATH/config/vocabularies/Project/accept.txt"

    printf 'A normal sentence.\n' > good.md
    printf 'BADWORD\n' > bad.md
    ${config.git-hooks.hooks.vale.entry} good.md
    if ${config.git-hooks.hooks.vale.entry} bad.md > alerts.txt; then
      echo "The built-in Vale hook should reject the forbidden word" >&2
      exit 1
    fi
    grep -q 'TestStyle.Forbidden' alerts.txt

    printf 'SECONDWORD\n' > second.md
    if vale second.md > second-alerts.txt; then
      echo 'The second package in the list should also be active' >&2
      exit 1
    fi
    grep -q 'SecondStyle.Forbidden' second-alerts.txt

    # Vale uses the environment from subdirectories, too. Accepted vocabulary
    # terms must suppress the custom rule after the local package is synced.
    mkdir nested
    (cd nested && vale ../good.md)
    printf 'GOODWORD\n' > accepted.md
    vale accepted.md
    vale sync
    test -f LocalPackage/styles/TestStyle/Forbidden.yml
    grep -q '^GOODWORD$' LocalPackage/styles/config/vocabularies/Project/accept.txt

    # Copy mode restores the declarative configuration on the next entry.
    printf '; manual edit\n' > "config dir/vale.ini"
    (${config.tasks."devenv:files".exec})
    grep -q '^; Generated by devenv' "config dir/vale.ini"
    vale --config "config dir/vale.ini" ls-config >/dev/null
  '';
}
